#Debug Messages
spring.output.ansi.enabled=ALWAYS

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

#JDBI SQL Log Output
app.enablesqllogging=true

spring.devtools.restart.enabled = true
spring.devtools.livereload.enabled=true
spring.main.lazy-initialization=true
spring.devtools.restart.exclude=logs/**